# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Heart_Sound_Results_System.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import*
from PyQt5.QtGui import*
from PyQt5.QtCore import*
from PyQt5.uic import loadUi
from threading import *

class ErrorActivity(QMainWindow):
    """
    A class for error activity

    Attribute
    ---------
    error: int
        To differentiate the error type

    Methods
    -------
    ConnectionError():
        To disply the messages for internet connection error
    HardwareError(self):
        To display the messages for hardware connection error
    """
    def __init__(self, error):
        """
        Parameter
        ---------
        error: int
            To differentiate the error type
        """
        super().__init__()
        self.error = error
        #Read the ui file
        loadUi("errorPage.ui",self)
        #remove title bar
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        #stick the window on the top
        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        
        scale_percent = 25#define 30% scale percent of original size
        oImage = QImage("Icon/Nursing home-pana.png")#read the image
        original_width = oImage.width()#extract width of the original image
        original_height = oImage.height()#extract height of the original image

        #Scale the image to small dimension 
        image_width = int(original_width * scale_percent / 100)#scale image horizontally
        image_height = int(original_width * scale_percent / 100)#scale image horizontally

        #Resize the image
        sImage = oImage.scaled(QSize(image_width,image_height))

        #set the image
        self.label_errorImageLarge.setPixmap(QtGui.QPixmap(sImage))
        scale_percent =40#define 40% scale percent of original size
        oImage = QImage("Icon/error.png")#read the image
        original_width = oImage.width()#extract width of the original image
        original_height = oImage.height()#extract height of the original image

        #Scale the image to small dimension 
        image_width = int(original_width * scale_percent / 100)#scale image horizontally
        image_height = int(original_width * scale_percent / 100)#scale image horizontally

        #Resize the image
        sImage = oImage.scaled(QSize(image_width,image_height))

        #set the image
        self.label_errorImageSmall.setPixmap(QtGui.QPixmap(sImage))

        #Design the error title
        errorTitle = """<p align="center"><span style="font-size:62pt; verticle-align:super; color:#EC7063;">Oops! </span></p>"""
        errorTitle2 = """<span style="font-size:22pt; verticle-align:super; color:#641E16;">nothing found......</span></p>"""

        #set the error title
        self.label_ErrorTextTitle.setText(errorTitle + "\n" + errorTitle2)

        #design the error title
        self.label_ErrorTextTitle.setStyleSheet("QLabel {font: 'Algerian';}")

        #set the alignment to center
        self.label_ErrorTextTitle.setAlignment(Qt.AlignCenter)
        self.label_errorImageSmall.setAlignment(Qt.AlignCenter)
        self.label_errorImageLarge.setAlignment(Qt.AlignCenter)

        #set the error message
        if self.error == 0:
            self.ConnectionError()
        else:
            self.HardwareError()
        #design the push button
        self.pushButton_ErrorButton.setStyleSheet("QPushButton{color:black;" 
                                      'font: 18pt "Nirmala UI";' +
                                      "border-style : solid;" +
                                      "border-radius: 15px;" +
                                      "background-color: rgba(149, 165, 166,50%);}"+
                                      "QPushButton:hover{background-color : #CB4335;" +
                                      "color: white;}")
        #set the text on the push button
        self.pushButton_ErrorButton.setText("Try Again")
        #set the functionality of the push button
        self.pushButton_ErrorButton.clicked.connect(lambda: self.close())#connect to close window function

    def ConnectionError(self):
        """
        To disply the messages for internet connection error
        """
        #Design the error message
        error_message1 = """<p align="center"><span style="font-size:20pt; verticle-align:super; color:#154360;"><strong>Internet not found!</strong></span></p>"""
        error_message2 = """<p align="center"><span style="font-size:14pt; verticle-align:super; color:#2E86C1;"><strong>Please check your internet connection.</strong></span></p>"""
        error_message3 = """<p align="center"><span style="font-size:14pt; verticle-align:super; color:#2E86C1;">Make sure that you are connecting to the network.</span></p>"""
        #set the error message
        self.label_ErrorTextMessage.setText(error_message1)
        self.label_ErrorText.setText(error_message2 +"\n"+error_message3+"\n")

    def HardwareError(self):
        """
        To display the messages for hardware connection error
        """
        #Design the error message
        error_message1 = """<p align="center"><span style="font-size:20pt; verticle-align:super; color:#154360;"><strong>Could not open port!</strong></span></p>"""
        error_message2 = """<p align="center"><span style="font-size:14pt; verticle-align:super; color:#2E86C1;"><strong>Only COM4 is supported!!!</strong></span></p>"""
        error_message3 = """<p align="center"><span style="font-size:14pt; verticle-align:super; color:#2E86C1;">Check the connectivity of your hardware sensor.</span></p>"""
        error_message4 = """<p align="center"><span style="font-size:14pt; verticle-align:super; color:#2E86C1;">Something went wrong when open the port 'COM4'!</span></p>"""
        error_message5 = """<p align="center"><span style="font-size:14pt; verticle-align:super; color:#2E86C1;">The system cannot find the file specified!</span></p>"""
        #set the error message
        self.label_ErrorTextMessage.setText(error_message1)
        self.label_ErrorText.setText(error_message2 +"\n"+error_message3+"\n"+error_message4+"\n"+error_message5)

class ErrorUI(QtCore.QThread):
    """
    A class for error GUI window

    ...

    Attributes
    ----------
    error : int
        The identifier to identify the error

    Methods
    -------
    run():
        Start the thread
    """
    def __init__(self, error):
        """
        Parameters
        ----------
        informations : list
            The information of the login user
        """
        super(ErrorUI, self).__init__()
        self.error = error

    def run(self):
        """
        Initialize and start the main activity interface window
        """
        self.error = ErrorActivity(self.error)
        self.error.show()        
